version: '2'
services:
  postgres:
    image: postgres:15.2
    container_name: matchbox_db
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: matchbox
      POSTGRES_PASSWORD: matchbox
      POSTGRES_DB: matchbox_db
    ports:
      - "5433:5432"
    networks:
      - intra
networks:
  intra:
    driver: bridge
