version: "2"
services:
    postgres:
        image: postgres:15.2
        container_name: matchbox_db
        volumes:
            - ./db/:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        networks:
            - intra

    backend:
        image: matchbox-back-img
        container_name: matchbox_backend
        build: ./backend
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        volumes:
            - ./BackEnd:/Backend/
            - /usr/Backend/node_modules
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            DATABASE_URL: ${DATABASE_URL}
            OAUTH_APP_URL: ${OAUTH_APP_URL}
            OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
            OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
            JWT_SECRET: ${JWT_SECRET}
            NODEMAILER_USER: ${NODEMAILER_USER}
            NODEMAILER_PASSWORD: ${NODEMAILER_PASSWORD}
            BACKEND_URL: ${BACKEND_URL}
            FRONT_URL: ${FRONT_URL}
        command: >
            bash -c " sleep 30 &&
                    npx prisma migrate deploy &&
                    npm start"
        networks:
            - intra

    frontend:
        image: matchbox-front-img
        container_name: matchbox-frontend
        build:
            context: ./frontend
        ports:
            - "4000:80"
        restart: unless-stopped
        networks:
            - intra
        # environment:
        #     REACT_APP_BASE_BACKEND_URL: ${REACT_APP_BASE_BACKEND_URL}

networks:
    intra:
        driver: bridge
